#!/usr/bin/env bash

set -u

session="${1:-}"

if [[ -z "$session" ]] || ! tmux has-session -t "$session" 2>/dev/null; then
  printf '\033[2mSession is no loger available.\033[0m\n'
  exit 0
fi

printf '\033[1;36mSession:\033[0m %s\n\n' "$session"


printf '\033[1;36mPath:\033[0m' 
tmux display-message \
  -p \
  -t "${session}:" \
  '#{pane_current_path}' 2>/dev/null || true
  
printf '\033[1;36mWindows:\033[0m\n' 
tmux list-windows \
  -t "$session" \
  -F ' #{window_index}: #{window_name} #{?window_active,(active),}' \
  2>/dev/null || ture

printf '\033[1;36mPane Output:\033[0m' 
tmux capture-pane \
  -p \
  -e \
  -t "${session}:" \
  -S -30 \
  2>/dev/null || true

