# IDE Enviroment Variable (ENV)
# Set enviroment varialbe equal first

# AGETNT
# AI_AGENT_CMD=Enter Agent command here!
# IDE_AGENT_WIDTH=Enter Agent Width custom!

# TERMINAL
# IDE_TERM_HEIGHT=Enter Terminal Height custom!
